### ISSUE TITLE
 Finder got an error: Can’t get disk (-1728)

### ISSUE THREAD

**Issue by EgorBlagov** [FibreFoX/javafx-gradle-plugin#139]
Hi,

Thanks for this plugin, I use it to build jfx app but facing the issue during build mac DMG image. the stack trace is below.
Its occasionally reproducible. I assume that it's not related to your project directly but maybe you have such experience.

I'd like to add that I have also some custom cleanups in build job, that unmounts and ejects disk that were mounted during the build, also it asks Finder to close some windows, and removes all created fxbundler* directories in $TMPDIR, don't know if it all is related, and don't know why gradle doesn't do it by itself.
```
:jar
:jfxJar
:jfxNative
The jar lib/jna-4.4.0.jar has a main class com.sun.jna.Native that does not match the declared main com.exalttech.trex.application.TrexApp
The jar lib/bsh-2.0b4.jar has a main class bsh.Console that does not match the declared main com.exalttech.trex.application.TrexApp
The jar lib/jna-platform-4.4.0.jar has a main class com.sun.jna.Native that does not match the declared main com.exalttech.trex.application.TrexApp
Preparing Info.plist: /var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler6944184335863367722/macosx/Info.plist
  Using default package resource [Bundle config file]  (add package/macosx/Info.plist to the class path to customize)
  Using custom package resource [icon]  (loaded from package/macosx/trex-stateless-gui.icns)
Creating app bundle: /Volumes/SSD/jenkins-home/workspace/trex-gui-mac/trex-stateless-gui/build/jfx/native/trex-stateless-gui.app
Running [security, find-certificate, -c, Developer ID Application: , -a]
Did not find a key matching 'Developer ID Application: '
  Config files are saved to /var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler6944184335863367722/macosx. Use them to customize package.
The jar lib/jna-4.4.0.jar has a main class com.sun.jna.Native that does not match the declared main com.exalttech.trex.application.TrexApp
The jar lib/bsh-2.0b4.jar has a main class bsh.Console that does not match the declared main com.exalttech.trex.application.TrexApp
The jar lib/jna-platform-4.4.0.jar has a main class com.sun.jna.Native that does not match the declared main com.exalttech.trex.application.TrexApp
Building DMG package for trex-stateless-gui
Preparing Info.plist: /var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler5533587845716767885/macosx/Info.plist
  Using default package resource [Bundle config file]  (add package/macosx/Info.plist to the class path to customize)
  Using custom package resource [icon]  (loaded from package/macosx/trex-stateless-gui.icns)
Running [security, find-certificate, -c, Developer ID Application: , -a]
Did not find a key matching 'Developer ID Application: '
  Config files are saved to /var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler5533587845716767885/macosx. Use them to customize package.
  Using custom package resource [dmg background]  (loaded from package/macosx/trex-stateless-gui-background.png)
  Using custom package resource [volume icon]  (loaded from package/macosx/trex-stateless-gui-volume.icns)
Using default package resource [script to run after application image is populated]  (add package/macosx/trex-stateless-gui-post-image.sh to the class path to customize)
Preparing dmg setup: /var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler5533587845716767885/macosx/trex-stateless-gui-dmg-setup.scpt
  Using default package resource [DMG setup script]  (add package/macosx/trex-stateless-gui-dmg-setup.scpt to the class path to customize)
 Creating DMG file: /Volumes/SSD/jenkins-home/workspace/trex-gui-mac/trex-stateless-gui/build/jfx/native/trex-stateless-gui-4.5.117372566.dmg
Running [/usr/bin/hdiutil, create, -quiet, -srcfolder, /var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler5533587845716767885/images/image-2364314852986941955, -volname, trex-stateless-gui, -ov, /var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler5533587845716767885/images/trex-stateless-gui-tmp.dmg, -fs, HFS+, -format, UDRW]
Running [/usr/bin/hdiutil, attach, /var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler5533587845716767885/images/trex-stateless-gui-tmp.dmg, -quiet, -mountroot, /var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler5533587845716767885/images]
Running [osascript, /var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler5533587845716767885/macosx/trex-stateless-gui-dmg-setup.scpt]
/var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler5533587845716767885/macosx/trex-stateless-gui-dmg-setup.scpt:63:67: execution error: Finder got an error: Can’t get disk "trex-stateless-gui". (-1728)
java.io.IOException: Exec failed with code 1 command [[osascript, /var/folders/1r/4_lzv7q51_z9dhxt6g_jf_380000gy/T/fxbundler5533587845716767885/macosx/trex-stateless-gui-dmg-setup.scpt] in unspecified directory
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:165)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)
	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)
	at com.oracle.tools.packager.mac.MacDmgBundler.buildDMG(MacDmgBundler.java:376)
	at com.oracle.tools.packager.mac.MacDmgBundler.bundle(MacDmgBundler.java:92)
	at com.oracle.tools.packager.mac.MacDmgBundler.execute(MacDmgBundler.java:556)
	at de.dynamicfiles.projects.gradle.plugins.javafx.tasks.workers.JfxNativeWorker.jfxnative(JfxNativeWorker.java:348)
	at de.dynamicfiles.projects.gradle.plugins.javafx.tasks.JfxNativeTask.jfxnative(JfxNativeTask.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:241)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:214)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:207)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by zeroDivider** [comment]
Maybe this can help: https://github.com/andreyvit/create-dmg/issues/43

**Comment by EgorBlagov** [comment]
@zeroDivider, Hi, thanks for your input
