### ISSUE TITLE
Could not generate a proxy class for class de.dynamicfiles.projects.gradle.plugins.javafx.tasks.JfxJarTask

### ISSUE THREAD

**Issue by maxd** [FibreFoX/javafx-gradle-plugin#19]
I am trying to integrate `javafx-gradle-plugin` with my multi-module project on Kotlin but when I execute `jfxRun` I see the following error:

```
test_javafx-gradle-plugin_kotlin git:(master) : ./gradlew clean jfxRun --stacktrace

FAILURE: Build failed with an exception.

* Where:
Build file '<projects dir>/test_javafx-gradle-plugin_kotlin/application/build.gradle' line: 7

* What went wrong:
A problem occurred evaluating project ':application'.
> Failed to apply plugin [id 'javafx-gradle-plugin']
   > Could not generate a proxy class for class de.dynamicfiles.projects.gradle.plugins.javafx.tasks.JfxJarTask.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':application'.
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
    at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:157)
    at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
    at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:162)
    at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
    at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
    at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
    at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:529)
    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:90)
    at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
    at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
    at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
    at org.gradle.internal.Factories$1.create(Factories.java:22)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
    at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
    at org.gradle.util.Swapper.swap(Swapper.java:38)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
    at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'javafx-gradle-plugin']
    at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:153)
    at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
    at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
    at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
    at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:35)
    at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
    at build_7fdxvpp4jfr13g4wm0m3ueyx0.run(<projects dir>/test_javafx-gradle-plugin_kotlin/application/build.gradle:7)
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
    ... 58 more
Caused by: org.gradle.api.GradleException: Could not generate a proxy class for class de.dynamicfiles.projects.gradle.plugins.javafx.tasks.JfxJarTask.
    at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:201)
    at org.gradle.api.internal.AbstractClassGenerator.generate(AbstractClassGenerator.java:64)
    at org.gradle.api.internal.project.taskfactory.TaskFactory.create(TaskFactory.java:115)
    at org.gradle.api.internal.project.taskfactory.TaskFactory.createTask(TaskFactory.java:77)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.createTask(AnnotationProcessingTaskFactory.java:101)
    at org.gradle.api.internal.project.taskfactory.DependencyAutoWireTaskFactory.createTask(DependencyAutoWireTaskFactory.java:39)
    at org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:62)
    at org.gradle.api.internal.tasks.DefaultTaskContainer.replace(DefaultTaskContainer.java:133)
    at de.dynamicfiles.projects.gradle.plugins.javafx.JavaFXGradlePlugin.apply(JavaFXGradlePlugin.java:46)
    at de.dynamicfiles.projects.gradle.plugins.javafx.JavaFXGradlePlugin.apply(JavaFXGradlePlugin.java:36)
    at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
    at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
    at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
    ... 69 more
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/tools/packager/PackagerException
    at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:67)
    at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:51)
    at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:31)
    at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:260)
    at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:216)
    at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:95)
    ... 81 more
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.tools.packager.PackagerException
    ... 87 more


BUILD FAILED

Total time: 0.868 secs
```

How to reproduce this problem:

1. Disable Gradle daemon for any case (`org.gradle.daemon=false` in `~/.gradle/gradle.properties`) and kill running daemon process
2. Clone repository: https://github.com/maxd/javafx-gradle-plugin_kotlin
3. Run `./gradlew clean jfxRun --stacktrace`

Will be shown error described above but I expect to see running application.

I have found workaround: just "grep" all `build.gradle` files and comment/uncomment lines marked by `(1)` string in comment. As you can see I just remove initialization of kotlin plugin from root module and move initialization to submodules. But I don't understand why this workaround works.

Seems like `javafx-gradle-plugin` and `kotlin` plugin has compatibility problems. Right?

**Comment by FibreFoX** [comment]
I will check this and report back. But just to make sure: what type of java are you using? OpenJDK? What platform?

**Comment by maxd** [comment]
Java was installed from Oracle JDK:

```
~ java -version

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

OS: OS X El Capitan 10.11.3 (15D21)

**Comment by FibreFoX** [comment]
Besides that being some old JDK , I can reproduce the behaviour, but it's not that easy to find this. It is possible, that my tweak with the jfx-ant-jarfile is way too hacky here. I'm injecting that file when injecting that jar-file when `apply plugin: 'javafx-gradle-plugin'` gets called

**Comment by maxd** [comment]
You are right. I have declared loading of `ant-javafx.jar` in root module and it fix problem:

```
diff --git a/build.gradle b/build.gradle
index 03754c7..4821f53 100644
--- a/build.gradle
+++ b/build.gradle
@@ -6,6 +6,7 @@ buildscript {
     dependencies {
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"

+        classpath files("${System.env.JAVA_HOME}/lib/ant-javafx.jar")
         classpath "de.dynamicfiles.projects.gradle.plugins:javafx-gradle-plugin:8.4.1"
     }
 }
```

Seems like this is more right way than [this](https://github.com/FibreFoX/javafx-gradle-plugin/blob/e41cc4daa37edd9b5673188be93e967cd9c83b61/src/main/java/de/dynamicfiles/projects/gradle/plugins/javafx/JavaFXGradlePlugin.java#L85) hack.

FYI: Bump JDK to 1.8.0_91.

**Comment by FibreFoX** [comment]
It might be more a problem of your build-script :) I have a working setup with your repository, just needs some polish. I'll commit that changes to the fork I just made and will report back here.

**Comment by FibreFoX** [comment]
@maxd here you go:
https://github.com/FibreFoX/javafx-gradle-plugin_kotlin/commit/eaec180be39256c4426daec73d78e603a5f16d98

In short: I moved some `apply`-ies into their corresponding build-scripts.

Does that fit your needs?

**Comment by maxd** [comment]
No, because I want to avoid copy-paste of configuration between all subprojects as recommended [here](http://www.petrikainulainen.net/programming/gradle/getting-started-with-gradle-creating-a-multi-project-build/) in `Removing Duplicate Configuration` section for example.

> It might be more a problem of your build-script :)

Could you please explain this?

**Comment by FibreFoX** [comment]
I've made a pull-requests for the requested changes: https://github.com/maxd/javafx-gradle-plugin_kotlin/pull/1

**Comment by maxd** [comment]
This is solution is appropriate but still has a copy-paste because need to declare `kotlin` plugin and some dependencies (i.e. `kotlin-stdlib`) in all subprojects. Will be better to declare them in one place (in root module) but `javafx-gradle-plugin` don't allow me to do it. 

Is it possible to add option to enable/disable call of `addJavaFXAntJARToGradleBuildpath` method? In this case I disable hack and add `ant-javafx.jar` manually as described above. What do you think about it?

**Comment by FibreFoX** [comment]
I found this [discussion about subprojects and buildscripts](https://discuss.gradle.org/t/buildscript-in-subprojects-ignored/2401). Gradle-plugins are part of the buldscript and not part of the real the dependencies, but only for the buildscripts, these plugins are applied to, but that implies that all libs are there ... .... which is not true for the `ant-javafx.jar`, because of the task-resolution ... it's a frustrating way of dependency-resolution. There is no way to specify some dependency being required to the plugin or changing the buildscript-dependencies .... and I refuse to find it a good way to include dependencies for some plugins to run as part of every project (that what my guts are telling me) ... and that's why I decided to move the "manipulation" of the `ant-javafx.jar` inside the apply-part of the plugin.

To make javafx-development more easy, I decided to include the `ant-javafx.jar` when applying the javafx-gradle-plugin, like the javafx-maven-plugin does (but in a different way of course), developers shouldn't need to add libs that are required for development, because the JDK is so scattered.

If you know a way to make a gradle-plugin saying what it's depends on, please let me know :) this is a real pain for me and I feel with you, that it's a very unpleasent way how this plugin does it.

There is no need to disable the call of `addJavaFXAntJARToGradleBuildpath`, because it does nothing if the jar already exists as part of the classloader. The problem-part is the addition of the new gradle-tasks by this plugin (which can't resolve properly, because the classes not being found).

As there are existing workarounds/fixes, I feel this isse is finished, but you might decide this.

**Comment by maxd** [comment]
ok, let's close this issue because I don't known how to fix it right.
