### ISSUE TITLE
Run possibly not working correctly / Integration with Intellij IDEA

### ISSUE THREAD

**Issue by Aqluse** [FibreFoX/javafx-gradle-plugin#80]
I stuck after I decided to move my Intellij IDEA JavaFX project to Gradle JavaFX.

When I try to run app with jfxRun task, I got this in console (and nothing else, app don't show)
![03-08-2017 194033](https://user-images.githubusercontent.com/13728921/28927464-0db427ea-7884-11e7-9590-02f4ed4374ed.png)
Immediately after I stop running
![03-08-2017 194044](https://user-images.githubusercontent.com/13728921/28927588-5ccc8566-7884-11e7-91f0-b58a54b3a12f.png)
A little time after I stop
![03-08-2017 194100](https://user-images.githubusercontent.com/13728921/28927598-66591c70-7884-11e7-9596-bef2346dd75a.png)

Tried to debug it - not even reach start() in main class. But if I change string parameter passed to getResource(), it throwing exceptions, so it is executed well, strange but still isn't reaching breakpoints in this line.

**Comment by FibreFoX** [comment]
This might have something to do with the way how Gradle is using their daemon. Normally a task does not require any deep interaction, it's for "working"-stuff.

As you are using Gradle 4, which has even more daemon-stuff, this might be a gradle4-problem. I suspect the daemon does something my plugin doesn't like.

Please add the verbose-switch to see more output (just inside the jfx-block), maybe you will get more details about what is happening.

**Comment by Aqluse** [comment]
@FibreFoX 
```
:compileJava
:processResources UP-TO-DATE
:classes
:jar
:jfxJar
:jfxRun
Running JavaFX Application
Running command: java -jar project-jfx.jar
The daemon will cancel the build.
Could not execute build using Gradle installation 'C:\Gradle\gradle-4.0.2'.
21:00:02: External task execution finished 'jfxRun'.

```

If I causing exceptions to be (text after exceptions output)
`
... 
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

:jfxRun FAILED`

I put JAVA_TOOL_OPTIONS in system variables because I got errors with russian commentaries in my code, not sure that it have an effect on, but extra info may be useful.

**Comment by FibreFoX** [comment]
@Aqluse can you check if adding `--no-daemon` does result in running your application?

```
gradle jfxRun --no-daemon
```

**Comment by Aqluse** [comment]
@FibreFoX 
Like that?
`runAppParameter = '--no-daemon'`

**Comment by FibreFoX** [comment]
No, as I wrote, just calling it from CLI
```
gradle jfxRun --no-daemon
```

**Comment by Aqluse** [comment]
@FibreFoX 
It showed me exceptions in my project code, I commented it and it launched successfully (without commented part ofc). Running it with simple Run also successful. There wasn't any exception before I setup Gradle, but I try to find why it happening. Anyway it even wasn't output without calling Run with no daemon and debug not working properly

**Comment by FibreFoX** [comment]
Can you try to set this:
```groovy
jfx {
    verbose = true
}
```

There should be more valuable stuff printed out.

**Comment by Aqluse** [comment]
@FibreFoX 
Commented (without application being closed):
```
D:\Projects\IntelliJIDEA_Projects\MusicSuite>gradle jfxRun --no-daemon
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
<========-----> 66% EXECUTING [8s]
> :jfxJar
> Task :jfxRun_TOOL_OPTIONS: -Dfile.encoding=UTF8> :jfxRun
Running JavaFX Application
Running command: java -jar project-jfx.jar
<==========---> 83% EXECUTING [59s]
> :jfxRun

```

Not Commented:
```
D:\Projects\IntelliJIDEA_Projects\MusicSuite>gradle jfxRun --no-daemon
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

> Task :compileJava
Note: D:\Projects\IntelliJIDEA_Projects\MusicSuite\src\main\java\aqlusesoftware\musicsuite\component\filetree\FiletreeController.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
<==========---> 83% EXECUTING [13s]
> :jfxRun                                        <==========---> 83% EXECUTING [18s]
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
                                                 Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:722)
        at javafx.scene.control.SingleSelectionModel.clearAndSelect(SingleSelectionModel.java:103)
        at javafx.scene.control.TabPane$TabPaneSelectionModel.lambda$new$17(TabPane.java:684)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
        at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
> Task :jfxRunafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
Running JavaFX Application
Running command: java -jar project-jfx.jar
<==========---> 83% EXECUTING [19s]
> :jfxRun
        at javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:102)
        at javafx.collections.ObservableListBase.addAll(ObservableListBase.java:245)
        at aqlusesoftware.musicsuite.component.ComponentTabPaneController.initialize(ComponentTabPaneController.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
        at aqlusesoftware.musicsuite.Main.getCenterTabPane(Main.java:66)
        at aqlusesoftware.musicsuite.Main.start(Main.java:44)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Thread.java:748)
Exception in Application start method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
        at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.jfoenix.skins.JFXTabPaneSkin$TabHeaderContainer.<init>(JFXTabPaneSkin.java:911)
        at com.jfoenix.skins.JFXTabPaneSkin$HeaderContainer.addTab(JFXTabPaneSkin.java:609)
        at com.jfoenix.skins.JFXTabPaneSkin$HeaderContainer.<init>(JFXTabPaneSkin.java:568)
        at com.jfoenix.skins.JFXTabPaneSkin.<init>(JFXTabPaneSkin.java:94)
        at com.jfoenix.controls.JFXTabPane.createDefaultSkin(JFXTabPane.java:65)
        at javafx.scene.control.Control.impl_processCSS(Control.java:872)
        at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
        at javafx.scene.Node.processCSS(Node.java:9058)
        at javafx.scene.Scene.doCSSPass(Scene.java:545)
        at javafx.scene.Scene.preferredSize(Scene.java:1643)
        at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
        at javafx.stage.Window$9.invalidated(Window.java:846)
        at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
        at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
        at javafx.stage.Window.setShowing(Window.java:922)
        at javafx.stage.Window.show(Window.java:937)
        at javafx.stage.Stage.show(Stage.java:259)
        at aqlusesoftware.musicsuite.Main.start(Main.java:46)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jfxRun'.
> There was an exception while executing JavaFX Application. Please check build-log.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 22s
5 actionable tasks: 4 executed, 1 up-to-date

```

**Comment by FibreFoX** [comment]
This means when having "verbose" being active (which should be the default while developing) and `--no-daemon` being present, this is what you needed to know?

**Comment by Aqluse** [comment]
@FibreFoX 
What you mean by 

> this is what you needed to know?

I don't understand

P.S. I put `verbose = true` line in jfx and called `gradle jfxRun --no-daemon` in terminal

**Comment by FibreFoX** [comment]
As far as I understood this issue, you wanted to know what happened when calling `jfxRun`. Setting verbose and non-daemon mode does show more information. If you wanted to know why your application does not behave as expected, I will need to have some visible source-code to check against.

**Comment by Aqluse** [comment]
@FibreFoX I don't really wanted to know why my application code didn't work right, because before Gradle setup it worked perfectly, but I wanted to figure out why Run/Debug (especially debug) tools started to fail.
My first problem was resources, since it stored beside .java files and Gradle wanted them to be in "resources" folder to be included into compiled project files. I solved this one. Then my very first loaded fxml-layout suddenly missed at all, I created it again. Now I got my Tabs (at least one of two) likely to be nulled even after initialization, I expect it in cause of loading fxml-resource as passed parameter to Tab's constructor, but all these resources are actually present in build/resources/... paths and all resources loaded before those Tabs was loaded properly even they are in subfolders of build/resources.

I'll check my project with latest Gradle 3.x version, as you said plugin isn't very optimised for newest version, then do some brainstorming if preceding won't help, then I'll get you project sources.

**Comment by Aqluse** [comment]
Project
https://mega.nz/#!W051WaKA!OsxNiU3gcBmgF0UtDp9sUr_ursoVpVT4rVvhyQN2rzU

**Comment by FibreFoX** [comment]
@Aqluse I've downloaded your project, you can delete it now. When I find something, I will report back to you.

**Comment by Aqluse** [comment]
The same problems with non-fx Java Gradle project in Intellij, in which I copied sources, libs and build.gradle text

**Comment by FibreFoX** [comment]
Now you lost me ... you are still using the gradle daemon. The task "jfxRun" is not compatible with the daemon, as that task was never thought of a real development-way, more than a quick-command for lazy execution.

So is this stil an issue with the plugin, or just related to your IDE/project?

**Comment by Aqluse** [comment]
@FibreFoX 
"The task "jfxRun" is not compatible with the daemon, as that task was never thought of a real development-way, more than a quick-command for lazy execution."
You mean that I shouldn't use plugin for running/debugging coding, but just to assemble it by plugin tasks and running/debugging with IDE built-in tasks or I'm mistaken?

**Comment by FibreFoX** [comment]
Currently there is no IDE-support, yes. This plugin was ment for the bundling-process, but I can see a lot of devs using this for more than just bundling. Nevertheless you can use your normal IDE-features for running/debugging.

**Comment by Aqluse** [comment]
@FibreFoX Okay, it changes problem a little bit. I wanted to use Gradle to simplify online libs dependencies setting, so if it would work like that - it's ok. Do you plan to integrate plugin deeper with IDE's?

**Comment by Nerjis** [comment]
![capture du 2019-01-05 23-43-33](https://user-images.githubusercontent.com/39071836/50730735-86eb3f80-1154-11e9-982f-bf2848c10486.png)
i have thise problem does anyone know how to solve it?
